#!/bin/bash

# List of function names
functions=(
  _putchar
  _islower
  _isalpha
  _abs
  _isupper
  _isdigit
  _strlen
  _puts
  _strcpy
  _atoi
  _strcat
  _strncat
  _strncpy
  _strcmp
  _memset
  _memcpy
  _strchr
  _strspn
  _strpbrk
  _strstr
)

# Compile each function
for function in "${functions[@]}"; do
  gcc -c -o "${function}.o" "${function}.c"
done

